[package]
name = "kotlin-parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kotlin-lexer = { path = "../kotlin-lexer" }
kotlin-ast = { path = "../kotlin-ast" }